### ISSUE TITLE
Failed to resolve: com.trendyol.showcase:showcase:0.9.5

### ISSUE THREAD

**Issue by muhammedelsami** [bilgehankalkan/showcase#8]
Hi, I'm trying to add the library to my project, I'm getting an error like this.

Failed to resolve: com.trendyol.showcase:showcase:0.9.5

------------------------

allprojects {
     repositories {
         ...
         maven { url 'https://jitpack.io' }
     }
}
because allprojects is not in root build.gradle file
maven { url 'https://jitpack.io' }
I am adding it to my settings.gradle file.

<img width="1102" alt="Screen Shot 2022-02-25 at 2 13 36 PM" src="https://user-images.githubusercontent.com/69201829/155705924-bb9e436d-37b3-43fe-a99a-4048ac8a8793.png">

**Comment by bilgehankalkan** [comment]
It should be `com.github.trendyol:showcase:{version}`.
